//routes test

//created user
###
POST https://rust-api-service.vercel.app/user
Content-Type: application/json

{
    "username": "jhon doe"
}

// greeting
###
GET https://rust-api-service.vercel.app

// Hello
###
GET https://rust-api-service.vercel.app/hello
